### ISSUE TITLE
Hey doesn't work for me

### ISSUE THREAD

**Issue by bcrigler** [d1slact0r/passwords-chrome2icloud#1]
I get this - 

"error "System Events got an error: Can’t get button \"Wachtwoorden\" of toolbar 1 of window 1 of application process \"Safari\"." number -1728 from button "Wachtwoorden" of toolbar 1 of window 1 of application process "Safari""

**Comment by bcrigler** [comment]
Actually, you can close this... I just realized this was optimized for the Dutch macbook so I forked it and converted it to English.  https://github.com/bcrigler/passwords-chrome2icloud

Hope you don't mind!

Thanks!
Brian

**Comment by bruvv** [comment]
It makes way more sense to do a PR to mine I would say ;) the more people contribute to this one the clearer the picture is.
