### ISSUE TITLE
【bug】在导出的条目包含“ftp://”时，Safari会在遇到这一行的时候崩溃

### ISSUE THREAD

**Issue by hanakisou4869** [d1slact0r/passwords-chrome2icloud#7]
解决方法只能是在导出后，手动删掉所有ftp开头的密码条目，再运行脚本导出。不知道能不能自动化处理这个，或者想办法令ftp条目也可被Safari导入呢？

**Comment by bruvv** [comment]
English ?

**Comment by hanakisou4869** [comment]
If chrome passwords contains items stars with "ftp:// ", then Safari will crash when script meets that line. I have to manually remove all "ftp://" items before running this.
